vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        cours:
            uri_prefix: /uploads/cours
            upload_destination: '%kernel.project_dir%/public/uploads/cours'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        blogs:
            uri_prefix: /uploads/blogs
            upload_destination: '%kernel.project_dir%/public/uploads/blogs'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        parametre:
            uri_prefix: /uploads/parametre
            upload_destination: '%kernel.project_dir%/public/uploads/parametre'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer